### ISSUE TITLE
Stops when using bot.clickWindow() or bot.closeWindow()

### ISSUE THREAD

**Issue by TheAirBlow** [PrismarineJS/MineflayerArmorManager#12]
# Info
- Stops working when using bot.clickWindow() or bot.closeWindow()
- The code below is dropping all items from inventory, and then plugin stops working
# Code
```js
      var slots = bot.inventory.slots
      for (var currSlot of slots) {
        if (currSlot == null) continue;
        bot.clickWindow(currSlot.slot, 0, 0, () => {
          bot.clickWindow(-999, 0, 0)
        })
        bot.closeWindow(slots)
        continue;
      }
```

**Comment by G07cha** [comment]
I'm not sure if we have this code in current version of armor manager. Are you reporting an existing issue or it's a question?

**Comment by TheAirBlow** [comment]
I mean, when I executing code like this, it stops work without any errors. Yes, this is an issue.

**Comment by G07cha** [comment]
That's interesting, thanks for reporting, I'll look into it.

**Comment by TheAirBlow** [comment]
I will check the code, if I find issue I try to fix it

**Comment by TheAirBlow** [comment]
Crap, this is coded using TypeScript

**Comment by G07cha** [comment]
Hasn't been able to reproduce it in the most recent version, please let me know if you encounter the issue again.
