### ISSUE TITLE
equipAll() is equiping one item at time

### ISSUE THREAD

**Issue by Saiv46** [PrismarineJS/MineflayerArmorManager#43]

**Comment by u9g** [comment]
How should it work?

**Comment by Saiv46** [comment]
**Expected behaviour**:
Bot takes and equps all best armor from inventory.

**Actual behaviour**:
Bot takes one best item from inventory and equips it. So `equipAll` needs to be called at least 4 times

**Comment by G07cha** [comment]
Should be resolved in v2.0.0, let me know if it's not the case.
