### ISSUE TITLE
Cannot read properties of undefined (reading 'equipAll')

### ISSUE THREAD

**Issue by UzayliGAMER** [PrismarineJS/MineflayerArmorManager#57]
i use armor manager for my bot but i updated my mineflayer and this error happened. 

node: 18.16.0
mineflayer: 4.9.0
server: paper 1.19.3

**Comment by G07cha** [comment]
@UzayliGAMER could you please share the minimal code that caused the issue? I wasn't able to reproduce it in `example.js` with latest version of Mineflayer.

**Comment by G07cha** [comment]
Closing in meanwhile, will be happy to reopen when the issue can be reproduced.
